name: Deploy Static Website to 1Panel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to 1Panel Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.SERVER_KEY }}
          port: 2218
          script: |
            set -e
            echo "===== 开始部署 daekun ====="
            git config --global --add safe.directory /opt/1panel/www/sites/daekun.vigo.co.kr/index
            cd /opt/1panel/www/sites/daekun.vigo.co.kr/index
            git fetch origin
            git reset --hard origin/main
            echo "===== daekun 部署完成 ====="
